# For info on getting the latest rdme version and obtaining your API_DEFINITION_ID,
# see our docs: https://docs.readme.com/docs/rdme#example-syncing-an-openapi-definition
name: Sync Kable Docs to ReadMe.io
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi kable-api-v1.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_API_DEFINITION_ID }}
